# This is the workflow for the gitpayd server
# Set environment variables
  # GITPAYD_OWNER - owner of the repo gitpayd is watching
  # GITPAYD_REPO - repo name
  # GITPAYD_HOST - ip of your gitpayd instance
  # GITPAYD_PORT - gitpayd port (default is 7777)
  # API_KEY - secret (LND admin macaroon)

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the dev branch
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Check the build
      - name: Install modules
        run: npm i
        
      - name: If you build it they will come
        run: npm run build
      
      # TODO: Run some test suite
      # - name: Mic check. Testing 1,2,3...
      #   run: npm run test

      # execute node.js script that 
        # use github REST API
        # get a list of issues
        # receive a list of prs as argument
        # merge pr
        # close issue
        # will parse the payment request and send payment
      - name: gitpayd noops doin a lil sum'
        env:
          GITPAYD_OWNER: ${{ secrets.GITPAYD_OWNER }}
          GITPAYD_REPO: ${{ secrets.GITPAYD_REPO }}
          GITPAYD_HOST: ${{ secrets.GITPAYD_HOST }}
          GITPAYD_PORT: ${{ secrets.GITPAYD_PORT }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
        echo running health check
        curl -ivk http://$GITPAYD_HOST:$GITPAYD_PORT/gitpayd/healh -H 'authorization: $API_KEY'
        node dist/noops.js

      # - name: Automatically Merge PR
      #   uses: plm9606/automerge_actions@1.2.2
      #   with:
      #     # The label name to automatically merge. Default is "automerge".
      #     label-name: develop
      #     # The number of reviewers to automatically merge. Default is 1.
      #     reviewers-number: 0
      #     # The merge method ("merge", "squash", "rebase"). Default is "merge"
      #     merge-method: merge
      #     # Let the bot delete the merged branch. true or false.
      #     auto-delete: false
      #     # GitHub WebHook Secret Token
      #     github-token: ${{ secrets.GITHUB_TOKEN }}    